#!/usr/bin/env sh
# .husky/pre-commit

# Format and stage frontend files
frontend_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'src/frontend/.*\.(ts|tsx)$' || true)
if [ -n "$frontend_files" ]; then
  pnpm dlx prettier --write $frontend_files
  git add $frontend_files
fi

# Format and stage backend files
backend_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E 'src/backend/.*\.(cs|csproj)$' || true)
if [ -n "$backend_files" ]; then
  dotnet format "src/backend/MysticMadness.sln" --include $backend_files
  git add $backend_files
fi
